import 'dart:ui';

import 'package:flutter/material.dart';

class AllData {

  static String WelcomeTitle="An unique way to express the heart's emotions through Shayari..!";
  static String WelcomeTitleBio="\"Life is a book, with each moment a new story,In every breath lies an unknown youth's glory.\"";
  static String WelcomeButton="Let's Start";

  static String AppbarHindi="शायरी";
  static String AppbarEnglish="Shayari";

  static String CategoryTitleHindi="सभी श्रेणियाँ";
  static String CategoryTitleEnglish="All Category";

  static List CategoryListHindi = [
    "दोस्ती शायरी",
    "मजेदार शायरी",
    "शुभ प्रभात शायरी",
    "शुभ रात्रि शायरी",
    "ज़िन्दगी शायरी",
    "सफलता शायरी",
    "मोटिवेशन शायरी",
    "वफ़ा शायरी",
    "बेवफाई शायरी",
    "याद शायरी",
    "गुलज़ार शायरी",
    "प्यार भरी शायरी",
    "शादी शायरी",
    "दुआ शायरी",
    "तन्हाई शायरी",
    "जन्मदिन शायरी",
    "त्यौहार शायरी",
    "देशभक्ति शायरी",
    "दर्द शायरी",
    "प्रेम शायरी",
  ];
  static List CategoryListEnglish = [
    "Friendship Shayari",
    "Funny Shayari",
    "Good Morning Shayari",
    "Good Night Shayari",
    "Life Shayari",
    "Success Shayari",
    "Motivational Shayari",
    "Loyalty Shayari",
    "Betrayal Shayari",
    "Memory Shayari",
    "Gulzar Shayari",
    "Romantic Shayari",
    "Wedding Shayari",
    "Prayer Shayari",
    "Loneliness Shayari",
    "Birthday Shayari",
    "Festival Shayari",
    "Patriotic Shayari",
    "Sad Shayari",
    "Love Shayari",
  ];

  static List CategoryShortBioListHindi = [
    "सच्चे रिश्तों की मिठास।",
    "हंसी का अनमोल तोहफा।",
    "एक नई सुबह की शुरुआत।",
    "मीठे सपनों की रात।",
    "सफर की अनकही बातें।",
    "मेहनत का फल सुनहरा।",
    "प्रेरणा की नई किरण।",
    "सच्चाई का असली रूप।",
    "दिल टूटने की दास्तान।",
    "बीते लम्हों की यादें।",
    "शब्दों का जादू बिखेरें।",
    "दिल की सच्ची बातें।",
    "प्यार और रिश्तों का मिलन।",
    "उम्मीद की एक नयी राह।",
    "अकेलेपन की अनसुनी कहानियां।",
    "शुभकामनाओं की सौगात।",
    "खुशियों का रंगीन संगम।",
    "देश प्रेम की लहर।",
    "दिल की गहराई में छुपा दर्द।",
    "दिल की धड़कनों का संगीत।",
  ];
  static List CategoryShortBioListEnglish = [
    "Sweet bonds of true relations.",
    "A gift of priceless laughter.",
    "Start your day fresh.",
    "Night of sweet dreams.",
    "Unspoken tales of the journey.",
    "Golden fruits of hard work.",
    "A spark of new hope.",
    "True essence of honesty.",
    "The tale of broken hearts.",
    "Nostalgic moments revived.",
    "Magic woven in words.",
    "True feelings of the heart.",
    "Uniting love and relationships.",
    "A new path of hope.",
    "Unheard stories of solitude.",
    "Blessings wrapped in wishes.",
    "A colorful blend of joy.",
    "The wave of national pride.",
    "Hidden pain of the heart.",
    "The music of heartbeats.",
  ];

  static List CategoryImageList = [
    [
      "Friendship1.jpg",
      "Friendship2.jpg",
      "Friendship3.jpg",
      "Friendship4.jpg",
      "Friendship5.jpg",
      "Friendship6.jpg",
      "Friendship7.jpg",
      "Friendship8.jpg",
      "Friendship9.jpg",
      "Friendship10.jpg",
    ],
    [
      "Funny1.jpg",
      "Funny2.jpg",
      "Funny3.jpg",
      "Funny4.jpg",
      "Funny5.jpg",
      "Funny6.jpg",
      "Funny7.jpg",
      "Funny8.jpg",
      "Funny9.jpg",
      "Funny10.jpg",
    ],
    [
      "Good_Morning1.jpg",
      "Good_Morning2.jpg",
      "Good_Morning3.jpg",
      "Good_Morning4.jpg",
      "Good_Morning5.jpg",
      "Good_Morning6.jpg",
      "Good_Morning7.jpg",
      "Good_Morning8.jpg",
      "Good_Morning9.jpg",
      "Good_Morning10.jpg",
    ],
    [
      "Good_Night1.jpg",
      "Good_Night2.jpg",
      "Good_Night3.jpg",
      "Good_Night4.jpg",
      "Good_Night5.jpg",
      "Good_Night6.jpg",
      "Good_Night7.jpg",
      "Good_Night8.jpg",
      "Good_Night9.jpg",
      "Good_Night10.jpg",
    ],
    [
      "Life1.jpg",
      "Life2.jpg",
      "Life3.jpg",
      "Life4.jpg",
      "Life5.jpg",
      "Life6.jpg",
      "Life7.jpg",
      "Life8.jpg",
      "Life9.jpg",
      "Life10.jpg",
    ],
    [
      "Success1.jpg",
      "Success2.jpg",
      "Success3.jpg",
      "Success4.jpg",
      "Success5.jpg",
      "Success6.jpg",
      "Success7.jpg",
      "Success8.jpg",
      "Success9.jpg",
      "Success10.jpg",
    ],
    [
      "Motivational1.jpg",
      "Motivational2.jpg",
      "Motivational3.jpg",
      "Motivational4.jpg",
      "Motivational5.jpg",
      "Motivational6.jpg",
      "Motivational7.jpg",
      "Motivational8.jpg",
      "Motivational9.jpg",
      "Motivational10.jpg",
    ],
    [
      "Loyalty1.jpg",
      "Loyalty2.jpg",
      "Loyalty3.jpg",
      "Loyalty4.jpg",
      "Loyalty5.jpg",
      "Loyalty6.jpg",
      "Loyalty7.jpg",
      "Loyalty8.jpg",
      "Loyalty9.jpg",
      "Loyalty10.jpg",
    ],
    [
      "Betrayal1.jpg",
      "Betrayal2.jpg",
      "Betrayal3.jpg",
      "Betrayal4.jpg",
      "Betrayal5.jpg",
      "Betrayal6.jpg",
      "Betrayal7.jpg",
      "Betrayal8.jpg",
      "Betrayal9.jpg",
      "Betrayal10.jpg",
    ],
    [
      "Memory1.jpg",
      "Memory2.jpg",
      "Memory3.jpg",
      "Memory4.jpg",
      "Memory5.jpg",
      "Memory6.jpg",
      "Memory7.jpg",
      "Memory8.jpg",
      "Memory9.jpg",
      "Memory10.jpg",
    ],
    [
      "Gulzar1.jpg",
      "Gulzar2.jpg",
      "Gulzar3.jpg",
      "Gulzar4.jpg",
      "Gulzar5.jpg",
      "Gulzar6.jpg",
      "Gulzar7.jpg",
      "Gulzar8.jpg",
      "Gulzar9.jpg",
      "Gulzar10.jpg",
    ],
    [
      "Romantic1.jpg",
      "Romantic2.jpg",
      "Romantic3.jpg",
      "Romantic4.jpg",
      "Romantic5.jpg",
      "Romantic6.jpg",
      "Romantic7.jpg",
      "Romantic8.jpg",
      "Romantic9.jpg",
      "Romantic10.jpg",
    ],
    [
      "Wedding1.jpg",
      "Wedding2.jpg",
      "Wedding3.jpg",
      "Wedding4.jpg",
      "Wedding5.jpg",
      "Wedding6.jpg",
      "Wedding7.jpg",
      "Wedding8.jpg",
      "Wedding9.jpg",
      "Wedding10.jpg",
    ],
    [
      "Prayer1.jpg",
      "Prayer2.jpg",
      "Prayer3.jpg",
      "Prayer4.jpg",
      "Prayer5.jpg",
      "Prayer6.jpg",
      "Prayer7.jpg",
      "Prayer8.jpg",
      "Prayer9.jpg",
      "Prayer10.jpg",
    ],
    [
      "Loneliness1.jpg",
      "Loneliness2.jpg",
      "Loneliness3.jpg",
      "Loneliness4.jpg",
      "Loneliness5.jpg",
      "Loneliness6.jpg",
      "Loneliness7.jpg",
      "Loneliness8.jpg",
      "Loneliness9.jpg",
      "Loneliness10.jpg",
    ],
    [
      "Birthday1.jpg",
      "Birthday2.jpg",
      "Birthday3.jpg",
      "Birthday4.jpg",
      "Birthday5.jpg",
      "Birthday6.jpg",
      "Birthday7.jpg",
      "Birthday8.jpg",
      "Birthday9.jpg",
      "Birthday10.jpg",
    ],
    [
      "Festival1.jpg",
      "Festival2.jpg",
      "Festival3.jpg",
      "Festival4.jpg",
      "Festival5.jpg",
      "Festival6.jpg",
      "Festival7.jpg",
      "Festival8.jpg",
      "Festival9.jpg",
      "Festival10.jpg",
    ],
    [
      "Patriotic1.jpg",
      "Patriotic2.jpg",
      "Patriotic3.jpg",
      "Patriotic4.jpg",
      "Patriotic5.jpg",
      "Patriotic6.jpg",
      "Patriotic7.jpg",
      "Patriotic8.jpg",
      "Patriotic9.jpg",
      "Patriotic10.jpg",
    ],
    [
      "Sad1.jpg",
      "Sad2.jpg",
      "Sad3.jpg",
      "Sad4.jpg",
      "Sad5.jpg",
      "Sad6.jpg",
      "Sad7.jpg",
      "Sad8.jpg",
      "Sad9.jpg",
      "Sad10.jpg",
    ],
    [
      "Love1.jpg",
      "Love2.jpg",
      "Love3.jpg",
      "Love4.jpg",
      "Love5.jpg",
      "Love6.jpg",
      "Love7.jpg",
      "Love8.jpg",
      "Love9.jpg",
      "Love10.jpg",
    ]
  ];


  static Map<String,List> ShayariMapLikeList={
    "FriendshipShayariAllListHindi":[
      "दोस्ती नाम है सुख-दुख की कहानी का, दोस्ती नाम है सदा मुस्कुराने का।",
      "दोस्ती वो नहीं जो जान देती है, दोस्ती वो भी नहीं जो मुस्कान देती है।",
      "दोस्ती का रिश्ता काँच सा होता है, हर वक्त इसमें प्यार का रंग होता है।",
      "सच्ची दोस्ती वही है, जो वक्त की हर रेत पर साथ चले।",
      "जिनके दिल सच्चे होते हैं, उनकी दोस्ती भी सच्ची होती है।",
      "दोस्ती वो एहसास है जो अनजाने में दिल से जुड़ जाता है।",
      "किसी के चेहरे की हंसी हो तुम, किसी की खुशी का एहसास हो तुम।",
      "दोस्ती में कोई शर्त नहीं होती, सिर्फ एक-दूसरे के लिए प्यार होता है।",
      "दिल से दोस्ती की जाए तो दुनिया हसीन लगने लगती है।",
      "दोस्ती एक ऐसा पौधा है, जिसे सिर्फ प्यार से सींचा जाता है।",
      "दोस्ती वो खुशी है जो दिल से दिल तक जाती है।",
      "दोस्ती का नाम दिलों को जोड़ने वाला रिश्ता है।",
      "दोस्त वही सच्चा होता है, जो वक्त पर साथ देता है।",
      "दोस्ती का मतलब ही होता है सच्चाई और वफादारी।",
      "सच्ची दोस्ती वही है जो वक्त की हर रेत पर बनी रहती है।",
      "दोस्ती वो रिश्ता है जो दिलों में बिना किसी स्वार्थ के जुड़ता है।",
      "दोस्ती एक अनमोल खजाना है, जिसे पाने के लिए किस्मत चाहिए।",
      "सच्चा दोस्त वही है जो आपकी हर खुशी और ग़म में साथ दे।",
      "दोस्ती के बिना जिंदगी अधूरी है, क्योंकि सच्चा दोस्त ही जिंदगी का हिस्सा है।",
      "दोस्ती का रिश्ता वही है, जो हमेशा साथ रहता है, चाहे हालात जैसे भी हों।"
    ],
    "FriendshipShayariAllListEnglish":[
      "Friendship is the bond of sharing joys and sorrows, It’s the name of always smiling.",
      "Friendship is not just a bond, it’s the bond of hearts that never ends.",
      "Friendship is a glass-like bond, filled with colors of love.",
      "True friendship is the one that walks with you on the sands of time.",
      "Those with pure hearts always have pure friendships.",
      "Friendship is that feeling which unknowingly connects hearts.",
      "You are the smile on someone's face, the joy in someone's heart.",
      "Friendship has no conditions, it is just love and care for one another.",
      "When hearts connect in friendship, the world seems more beautiful.",
      "Friendship is a plant that can only be nurtured with love.",
      "Friendship is the joy that flows from heart to heart.",
      "Friendship is the bond that connects hearts without words.",
      "A true friend is the one who stands by you in tough times.",
      "Friendship means truth and loyalty.",
      "True friendship is the one that remains intact on the sands of time.",
      "Friendship is the bond that connects souls selflessly.",
      "Friendship is a priceless treasure, only the fortunate ones find.",
      "A true friend is the one who shares both your joys and sorrows.",
      "Life without friendship is incomplete, for a true friend is a part of life.",
      "Friendship is the bond that stays strong no matter what the circumstances are."
    ],

    "FunnyShayariAllListHindi": [
      "इश्क़ का तो पता नहीं, पर हाँ, जब से तुझे देखा है, राशन कार्ड का पैसा कम पड़ गया है।",
      "तू तो कहती थी कि तुझे मेरी आदत है, फिर क्या हुआ? अब पेट में दर्द क्यों नहीं होता?",
      "कभी उसको भी बुला लो जो हमारे दिल में है, अगर ना मिले, तो हमें चाय पिला देना।",
      "इश्क़ हो या आलू के पराठे, जब तक गर्म ना हो, मज़ा नहीं आता।",
      "मोहब्बत में धोखा मिलने पर भी इंसान हंसता है, जैसे ताजमहल के नीचे बैठकर भेलपुरी खाना।",
      "दिल तो पत्थर का है, लेकिन मुँह से गालियां खूब निकलती हैं।",
      "तेरे इश्क़ में ऐसी कशिश है कि इधर खाना बनाया और उधर जल गया।",
      "तेरे प्यार में इतना बोर हो गया हूँ, कि अब पकोड़े और चाय ही मेरे सहारे हैं।",
      "दिल की लगी बुझाने चला था, पर रस्ते में चाय की दुकान दिख गई।",
      "इश्क़ के दो ही रंग होते हैं, एक हरा और दूसरा लाला, पहला रंग तब आता है जब जेब में पैसा होता है।",
      "बेवफ़ा तो नहीं थे, बस आलसी थे, इसलिए जवाब नहीं दिया।",
      "तू कहती है कि मेरा दिल बहुत अच्छा है, क्या सच में? फिर तो तेरे दिल का टेस्ट करवाना पड़ेगा।",
      "हमने प्यार भी किया बड़े सलीके से, जब चाय ठंडी हुई, तब पीकर छोड़ दिया।",
      "तू बोलती है कि मेरी बातें समझ में नहीं आती, तो फिर तू यहाँ पढ़ाई क्यों कर रही है?",
      "तू कहती है कि मुझसे मोहब्बत नहीं करती, कोई बात नहीं, हम तो चाय वाले हैं।",
      "मेरे दोस्त ने पूछा प्यार क्या है? मैंने कहा, जैसे चाय में चीनी कम हो और तुमसे प्यारा जवाब नहीं।",
      "तेरे नखरे भी ऐसे हैं जैसे गर्मियों में बिजली चली जाए और कूलर बंद हो जाए।",
      "इश्क़ तो हम भी कर लेते, पर दिल का नेट पैक खत्म हो गया था।",
      "तेरे इश्क़ में इतने पागल हो गए हैं कि तेरी गली का कुत्ता भी दोस्त लगने लगा है।",
      "तू कहती है कि तुझसे दूर जाना चाहूं, पर मैं तो पास वाली चाय की दुकान तक जाता हूँ।"
    ],
    "FunnyShayariAllListEnglish": [
      "I don’t know about love, but ever since I saw you, my grocery money seems to be running out.",
      "You used to say you were addicted to me, what happened now? Why doesn't your stomach hurt anymore?",
      "Call the one who resides in my heart, and if they don’t come, at least offer me some tea.",
      "Love is like a hot paratha; it only feels good when it’s fresh and warm.",
      "Even after betrayal in love, people laugh, like eating snacks under the Taj Mahal.",
      "My heart might be made of stone, but I still know how to throw some epic insults.",
      "There's so much pull in your love that I ended up burning my food.",
      "I’m so bored in your love that now all I have left are snacks and tea.",
      "I was on my way to extinguish the fire in my heart, but I got distracted by a tea stall.",
      "Love has two colors: green for when you're broke, and red when you're in debt.",
      "I wasn’t unfaithful, I was just lazy, so I didn’t respond.",
      "You say my heart is good? Really? Let’s get your heart tested for sure!",
      "I loved in a very classy way—when the tea got cold, I left it.",
      "You say you don’t understand my talks, then why are you still here studying?",
      "You say you don’t love me, well that’s okay—I’m just here for the tea.",
      "My friend asked what love is. I replied, 'It’s like having less sugar in tea and still enjoying it.'",
      "Your tantrums are like the power going out during summer, leaving the cooler off.",
      "I was about to fall in love, but my heart’s data pack expired.",
      "I’m so crazy in love with you that even the dog in your street feels like a friend.",
      "You say I should go far away from you, but I only go as far as the nearest tea shop."
    ],

    "Good_MorningShayariAllListHindi": [
      "सपनों का जहाँ अब छोड़ भी दो, हुई सुबह अब जाग भी जाओ।",
      "हर सुबह एक नई शुरुआत होती है, आईये इसे हंसी-खुशी से शुरू करें।",
      "फूलों की तरह मुस्कुराओ, सुबह की तरह खिलो, और दिन भर खुश रहो।",
      "सूरज की किरने तेरे चेहरे पर मुस्कान लाए, यही दुआ है हमारी कि हर सुबह तेरी खुशियों से भरी हो।",
      "उठो सुबह की ताजगी से अपना दिन बनाओ, और सबकी जिंदगी में खुशियां लाओ।",
      "सुप्रभात! जिंदगी में हमेशा खुश रहो, क्योंकि मुस्कान से ही सभी समस्याओं का हल होता है।",
      "हर दिन एक नई उम्मीद है, इसे जी भर कर जियो। सुप्रभात!",
      "सुप्रभात! भगवान करे आज का दिन आपके लिए ढेर सारी खुशियाँ लेकर आए।",
      "एक प्यारी सी सुबह आई है, साथ में बहुत सारा प्यार लाई है।",
      "उठो और चमको, हर सुबह एक नई सफलता की ओर बढ़ने का मौका है।",
      "सूरज की पहली किरण आपको ऊर्जावान बनाए, और आपका दिन मंगलमय हो।",
      "सुबह की शांति और खुशबू आपको पूरे दिन तरोताजा रखे।",
      "जागिए और अपने सपनों को पूरा करने के लिए कदम बढ़ाइए।",
      "सुप्रभात! भगवान करे आपका दिन प्रेम और शांति से भरा हो।",
      "सुबह की किरणों की तरह चमकते रहो, और आगे बढ़ते रहो।",
      "एक नई सुबह, एक नई शुरुआत और अनगिनत अवसर। सुप्रभात!",
      "सपनों को हकीकत में बदलने के लिए उठो और अपने दिन की शुरुआत करो।",
      "आज का दिन खुशियों और सकारात्मकता से भरा हो। सुप्रभात!",
      "सूरज की पहली किरण के साथ आपका दिन शुभ हो।",
      "हर सुबह आपकी नई सफलता की ओर बढ़ने का संकेत है।"
    ],
    "Good_MorningShayariAllListEnglish": [
      "Wake up and shine, it's time to make your dreams come true. Good Morning!",
      "Every morning brings a new blessing, make sure to cherish it.",
      "Good morning! Let the sunshine fill your heart with joy and warmth.",
      "May this morning bring you endless joy and happiness. Good morning!",
      "Rise and shine, it's a beautiful day ahead. Good morning!",
      "Every sunrise brings a new opportunity, grab it and make the most of it. Good morning!",
      "May your day be filled with positivity, smiles, and success. Good morning!",
      "A new day, a new hope, and a fresh start. Good morning!",
      "Wishing you a wonderful morning filled with peace and happiness.",
      "Good morning! Let the first ray of sunshine brighten your path to success.",
      "May the morning breeze fill your heart with peace. Good morning!",
      "Good morning! Start your day with a smile and see how everything falls in place.",
      "Every morning is a new beginning. Have a great day ahead!",
      "Good morning! May your day be filled with positive vibes and happiness.",
      "Let the morning sun remind you that life is beautiful. Good morning!",
      "Good morning! It's time to rise and shine and chase your dreams.",
      "Sending you warm wishes for a wonderful morning and a beautiful day.",
      "Good morning! A day full of opportunities is waiting for you.",
      "May your day be as bright as the morning sun. Good morning!",
      "Wishing you a day filled with love, joy, and laughter. Good morning!"
    ],

    "Good_NightShayariAllListHindi": [
      "रात का चाँद आपकी नींद को प्यारा बना दे, और आपकी हर एक रात मीठे सपनों से भरी हो। शुभ रात्रि!",
      "सितारों की चमक आपके सपनों को सजाए, और चाँद की रोशनी आपके दिल को सुकून दे। शुभ रात्रि!",
      "रात की ठंडी हवा आपको सुकून दे, और आपकी नींद को मिठास से भर दे। शुभ रात्रि!",
      "रात का सन्नाटा और चाँद की रोशनी आपको प्यारे सपनों में ले जाए। शुभ रात्रि!",
      "सितारों की चमक से आपकी रात रोशन हो, और आपके सपने मीठे हों। शुभ रात्रि!",
      "चाँद की चांदनी आपके सपनों को सजाए और आपके दिन की थकान दूर करे। शुभ रात्रि!",
      "हर रात आपको प्यारे सपनों की दुनिया में ले जाए और सुबह आप नई उम्मीदों से जागें। शुभ रात्रि!",
      "नींद में भी आपको सुकून और चैन मिले, ये मेरी दुआ है। शुभ रात्रि!",
      "आपकी रात शांति से भरी हो, और आपका मन सुकून से भरा हो। शुभ रात्रि!",
      "सो जाओ प्यारी सी रात आई है, सपनों में मुलाकात की बारी आई है। शुभ रात्रि!",
      "सितारे आपको मीठे सपनों का रास्ता दिखाएं और चाँदनी आपकी रात को सजाए। शुभ रात्रि!",
      "रात का सन्नाटा और चाँद की रोशनी आपकी थकान दूर करे। शुभ रात्रि!",
      "आपकी रातें मीठे सपनों से भरी हों और सुबहें नई ताजगी से। शुभ रात्रि!",
      "सितारों से भरी ये रात आपको सुकून दे और सुबह नई उमंग से भर दे। शुभ रात्रि!",
      "रात का अंधेरा जितना गहरा हो, आपके सपने उतने ही प्यारे हों। शुभ रात्रि!",
      "चाँद की हल्की रोशनी आपको मीठी नींद दे और सितारे आपके सपनों को सजाएं। शुभ रात्रि!",
      "सपनों की दुनिया में आपको हर खुशी मिले और सुबह आपका दिन खुशियों से भरा हो। शुभ रात्रि!",
      "चाँदनी की ठंडक से आपकी रात खूबसूरत हो और सितारों की चमक से आपके सपने सजें। शुभ रात्रि!",
      "रात का सुकून आपको प्यारे सपनों में ले जाए और सुबह आपका दिन उमंग से भरा हो। शुभ रात्रि!",
      "रात की ताजगी और ठंडी हवा आपके मन को सुकून दे, और आपकी नींद मीठी हो। शुभ रात्रि!"
    ],
    "Good_NightShayariAllListEnglish": [
      "As the stars twinkle in the sky, may your dreams be filled with peace. Good night!",
      "Let the moonlight guide you to the land of sweet dreams. Good night!",
      "May the night bring you restful sleep and peaceful dreams. Good night!",
      "Wishing you a night filled with serene moments and a restful sleep. Good night!",
      "Let the stars be your blanket and the moon your light as you sleep tight. Good night!",
      "Good night! May the calm of the night bring you sweet dreams and a peaceful mind.",
      "As the world falls asleep, may your mind find rest and your heart find peace. Good night!",
      "May your dreams be as lovely as the night, and your sleep as calm as the stars. Good night!",
      "Wishing you a night filled with calm and dreams that take you to beautiful places. Good night!",
      "Sleep tight and dream big, for tomorrow is another chance to shine. Good night!",
      "Let the night embrace you with its calmness, and may your dreams be sweet. Good night!",
      "Good night! May the stars keep watch over you as you drift into a peaceful sleep.",
      "Close your eyes and relax, let the night bring you peace and joy. Good night!",
      "May your night be peaceful, your dreams sweet, and your rest deep. Good night!",
      "Wishing you a night of rest and a morning full of energy. Good night!",
      "May your dreams be bright, your heart light, and your sleep restful. Good night!",
      "Good night! Let the stars fill your dreams with hope and peace.",
      "As the night sets in, let your worries drift away and your dreams soar high. Good night!",
      "Wishing you a peaceful sleep and dreams full of happiness. Good night!",
      "Good night! May the night bring you comfort and the morning bring you joy."
    ],

    "LifeShayariAllListHindi": [
      "जिंदगी में जो हासिल करना हो, उसे खुद से ही शुरू करना होता है।",
      "हर लम्हा जिंदगी का एक नया सबक देता है, बस समझने का हुनर चाहिए।",
      "जिंदगी में अगर कुछ सीखना है तो अपने अतीत से सीखो।",
      "जिंदगी में मुश्किलें आती हैं, ताकि आप मजबूत बन सकें।",
      "जिंदगी का हर दिन एक नया मौका होता है, खुद को बेहतर बनाने का।",
      "रास्ते बदलते रहेंगे, लेकिन मंजिल का हौसला कभी नहीं टूटना चाहिए।",
      "खुश रहना है तो दूसरों की बातों पर ध्यान देना छोड़ दो।",
      "जिंदगी छोटी है, इसे प्यार और हंसी के साथ जियो।",
      "जिंदगी में हार मानना आसान है, लेकिन जीतने की कोशिश में मजा है।",
      "जिंदगी की असली खूबसूरती अपने सपनों को साकार करने में है।",
      "हर मुश्किल रास्ता आपको कामयाबी के करीब लाता है।",
      "जिंदगी वही है जो आप खुद बनाते हो, बस हिम्मत मत हारो।",
      "जिंदगी के हर मोड़ पर कुछ न कुछ सिखने को मिलता है।",
      "जिंदगी में असली जीत वही है, जब आप खुद से खुश हों।",
      "जो मुश्किलों से भागते हैं, जिंदगी उन्हें और मुश्किल बनाती है।",
      "जिंदगी में कामयाबी हासिल करने के लिए जुनून चाहिए।",
      "जिंदगी की हर सुबह एक नया अवसर लेकर आती है।",
      "हर लम्हा जी भर कर जियो, क्योंकि जिंदगी लौट कर नहीं आती।",
      "जिंदगी का असली मजा चुनौतियों का सामना करने में है।",
      "जिंदगी में वही सफल होते हैं, जो अपने रास्ते खुद बनाते हैं।"
    ],
    "LifeShayariAllListEnglish": [
      "Life is not about waiting for the storm to pass, but learning to dance in the rain.",
      "Every moment in life is a new opportunity to grow and become better.",
      "Life is a journey with ups and downs, but it’s the ride that counts.",
      "The beauty of life is in its imperfections; embrace them.",
      "Life is short, so make every second count and live it to the fullest.",
      "Life’s biggest lessons come from the toughest times, so never stop learning.",
      "Success in life is not the destination, but the journey that makes it worthwhile.",
      "In life, the greatest wealth is not money, but the memories you create.",
      "Life is all about the choices you make and the paths you choose to follow.",
      "Happiness in life is not by chance, but by the choices you make every day.",
      "Life is a canvas, and you are the artist. Paint it with the colors of joy.",
      "Life is not measured by the number of breaths you take, but by the moments that take your breath away.",
      "In the end, it’s not the years in your life that count, but the life in your years.",
      "Life is like a book, each day a new page, each year a new chapter.",
      "Live your life with purpose and passion, and everything else will fall into place.",
      "Life’s challenges are not meant to break you but to make you stronger.",
      "Life is too precious to waste on regrets. Embrace every moment.",
      "Life is what happens while you’re busy making other plans.",
      "The key to a happy life is not having everything, but appreciating what you have.",
      "Life is a gift, make sure you unwrap it with joy and live it fully."
    ],

    "SuccessShayariAllListHindi": [
      "सफलता का राज़ है मेहनत और धैर्य, हार नहीं मानने का जज्बा रखना।",
      "जो लक्ष्य तय कर लेते हैं, वो ही सच्ची सफलता की ओर बढ़ते हैं।",
      "सफलता के रास्ते में कठिनाइयाँ आएंगी, पर वो ही सच्चा विजेता है जो डटकर सामना करे।",
      "सपने वो नहीं जो सोते वक्त आते हैं, सपने वो हैं जो आपको सोने नहीं देते।",
      "हर छोटी सफलता एक बड़ी सफलता की नींव रखती है।",
      "सफलता की सीढ़ी पर पहला कदम हमेशा खुद पर विश्वास करना होता है।",
      "सपनों की पूर्ति मेहनत से होती है, इसलिए मेहनत का कोई विकल्प नहीं।",
      "सफलता की खुशबू उस मेहनत से आती है, जो आप दिन-रात करते हैं।",
      "सफलता कभी भी आसानी से नहीं मिलती, इसे पाने के लिए पसीना बहाना पड़ता है।",
      "सफलता उसी की होती है, जो मेहनत करने से नहीं चूकता।",
      "सपने वो नहीं जो आंखों में आते हैं, सपने वो हैं जो आपको जगाते हैं।",
      "जो लोग कठिनाईयों से डरते नहीं, वही सच्चे विजेता बनते हैं।",
      "सफलता की चाह रखने वालों को कभी हार नहीं माननी चाहिए।",
      "सपने देखने वाले महान बनते हैं, क्योंकि वो खुद पर विश्वास रखते हैं।",
      "सफलता की ओर बढ़ने वाले कदम कभी थमते नहीं।",
      "जो खुद पर विश्वास करते हैं, वो ही असंभव को संभव बना देते हैं।",
      "सफलता का कोई शॉर्टकट नहीं होता, मेहनत ही इसका रास्ता है।",
      "सपने देखने से कुछ नहीं होता, उन्हें पूरा करने के लिए मेहनत करनी पड़ती है।",
      "हर कदम पर सफलता पाने का हौसला रखो, क्योंकि तुम्हारे अंदर वो ताकत है।",
      "सफलता उस चीज़ का नाम है, जो खुद को बार-बार साबित करने में है।"
    ],
    "SuccessShayariAllListEnglish": [
      "Success is not the key to happiness. Happiness is the key to success.",
      "The road to success is dotted with many tempting parking spaces.",
      "Success is the sum of small efforts, repeated day in and day out.",
      "Don’t be afraid to give up the good to go for the great.",
      "Success usually comes to those who are too busy to be looking for it.",
      "Success is not final, failure is not fatal: It is the courage to continue that counts.",
      "Your attitude, not your aptitude, will determine your altitude.",
      "The only limit to our realization of tomorrow will be our doubts of today.",
      "Success is walking from failure to failure with no loss of enthusiasm.",
      "The way to get started is to quit talking and begin doing.",
      "Success is how high you bounce when you hit bottom.",
      "Success is not in what you have, but who you are.",
      "The secret of success is to be ready when your opportunity comes.",
      "Success is not about how much money you make, but the difference you make in people's lives.",
      "Success is not about the destination, but the journey you take to get there.",
      "Dream big and dare to fail; that’s how success is achieved.",
      "Success is the result of perfection, hard work, learning from failure, loyalty, and persistence.",
      "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
      "Success is a journey, not a destination; the doing is often more important than the outcome.",
      "The only place where success comes before work is in the dictionary."
    ],

    "MotivationalShayariAllListHindi": [
      "जिंदगी में हर कदम पर कुछ न कुछ सिखने को मिलता है, बस उन्हें समझने की जरूरत है।",
      "अगर आप अपनी मेहनत पर विश्वास करते हैं, तो कोई भी सपना असंभव नहीं।",
      "सपने वो नहीं जो सोते वक्त आते हैं, सपने वो हैं जो आपको सोने नहीं देते।",
      "अगर आप हार नहीं मानेंगे, तो सफलता आपके कदम चूमेगी।",
      "हर मुश्किल के पीछे एक नया सबक छिपा होता है, उसे पहचानना ही सफलता है।",
      "कामयाबी की सीढ़ी पर पहला कदम खुद पर विश्वास करना है।",
      "खुद को कमजोर समझना सबसे बड़ा पाप है, आप में अद्भुत क्षमता है।",
      "कड़ी मेहनत का फल मीठा होता है, बस धैर्य रखें और आगे बढ़ते रहें।",
      "सपने देखने से पहले मेहनत करना सीखें, सफलता आपके कदम चूमेगी।",
      "जिसने कभी हार नहीं मानी, उसकी जीत निश्चित है।",
      "हर सुबह एक नया अवसर लेकर आती है, उसे हाथ से जाने मत दो।",
      "अगर आप ठान लें तो कोई भी चीज़ असंभव नहीं।",
      "संघर्ष से भागो मत, यही आपको मजबूत बनाएगा।",
      "जो असफलता से डरते हैं, वो कभी सफल नहीं हो सकते।",
      "अपने लक्ष्य के प्रति ईमानदार रहो, सफलता आपके पास खुद चलकर आएगी।",
      "सफलता की कुंजी है कभी हार न मानना।",
      "जिंदगी में चुनौतियों का सामना करना ही असली बहादुरी है।",
      "खुद पर विश्वास रखें, आपके सपने सच हो सकते हैं।",
      "अगर आप सही दिशा में मेहनत करेंगे, तो मंजिल खुद-ब-खुद आपके पास आएगी।",
      "हर नया दिन एक नई शुरुआत है, इसे भुनाना मत भूलिए।"
    ],
    "MotivationalShayariAllListEnglish": [
      "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
      "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
      "Don't wait for opportunity. Create it.",
      "The future belongs to those who believe in the beauty of their dreams.",
      "Hardships often prepare ordinary people for an extraordinary destiny.",
      "Your limitation—it’s only your imagination.",
      "Push yourself, because no one else is going to do it for you.",
      "Great things never come from comfort zones.",
      "Dream it. Wish it. Do it.",
      "Success doesn’t just find you. You have to go out and get it.",
      "The harder you work for something, the greater you’ll feel when you achieve it.",
      "Dream bigger. Do bigger.",
      "Don’t stop when you’re tired. Stop when you’re done.",
      "Wake up with determination. Go to bed with satisfaction.",
      "Do something today that your future self will thank you for.",
      "Little things make big days.",
      "It’s going to be hard, but hard does not mean impossible.",
      "Don’t wait for the perfect moment. Take the moment and make it perfect.",
      "The secret to getting ahead is getting started.",
      "What you get by achieving your goals is not as important as what you become by achieving your goals."
    ],

    "LoyaltyShayariAllListHindi": [
      "वफा का नाम सुनते हैं, पर कम ही इसे निभाते हैं।",
      "लoyalty वो रिश्ता है, जो दिल से दिल तक जाता है।",
      "हर किसी का वादा टूटता है, लेकिन सच्ची वफादारी कभी नहीं।",
      "जो अपने होते हैं, वो हर हाल में साथ निभाते हैं।",
      "वफादारी की कीमत वो ही समझता है, जिसे कभी प्यार मिला हो।",
      "लोग कहते हैं वफा जरूरी है, पर असल में वफादार लोग ही जरूरी हैं।",
      "सच्चा प्यार वही है, जो वफादारी की कसौटी पर खरा उतरता है।",
      "जब दिल में वफादारी होती है, तब रिश्ते और भी मजबूत हो जाते हैं।",
      "लoyalty एक ऐसा फूल है, जो कभी मुरझाता नहीं।",
      "सच्ची वफादारी से बड़ा कोई तोहफा नहीं।",
      "साथ रहने से नहीं, बल्कि एक-दूसरे की वफादारी से रिश्ते मजबूत होते हैं।",
      "जो वफा करते हैं, उनका दिल हमेशा सच्चा होता है।",
      "लोग अपनी जरूरतों के लिए साथ रहते हैं, पर वफादार वही हैं जो बिना स्वार्थ के रहते हैं।",
      "हर वफा की कहानी होती है, पर कुछ कहानियाँ बेमिसाल होती हैं।",
      "वफादार दोस्त वो होते हैं, जो बुरे समय में साथ नहीं छोड़ते।",
      "जिन्हें वफादारी का मतलब नहीं पता, उन्हें प्यार नहीं मिला।",
      "सच्ची वफादारी कभी खत्म नहीं होती, वो हमेशा याद रहती है।",
      "लोग रिश्तों में वफादारी ढूंढते हैं, लेकिन खुद को वफादार बनाना भूल जाते हैं।",
      "वफादार रहो, क्योंकि यही आपकी पहचान है।",
      "एक वफादार दिल ही सबसे बड़ा तोहफा है।"
    ],
    "LoyaltyShayariAllListEnglish": [
      "Loyalty is not just a word; it’s a way of life.",
      "True loyalty is rare; it’s the bond that withstands the test of time.",
      "In a world full of temporary things, you are my forever.",
      "Loyalty is the foundation of any strong relationship.",
      "A loyal heart is worth its weight in gold.",
      "Trust is built on loyalty, and loyalty is built on trust.",
      "Loyalty means standing by each other, come what may.",
      "In times of trouble, loyalty shines the brightest.",
      "Your loyalty is a reflection of your character.",
      "Loyalty is not about being together; it’s about being there for each other.",
      "True loyalty never fades; it only grows stronger.",
      "In the journey of life, loyal friends are the best companions.",
      "Loyalty is a promise that never breaks.",
      "With loyalty comes respect, and with respect comes love.",
      "Loyalty is the glue that holds relationships together.",
      "A loyal partner is a treasure worth cherishing.",
      "In a world of betrayal, be a beacon of loyalty.",
      "Loyalty means being honest, even when it’s hard.",
      "True loyalty stands firm in the face of adversity.",
      "Loyalty is a rare gem; cherish it when you find it.",
    ],

    "BetrayalShayariAllListHindi": [
      "धोखा वो है, जो अपने अपने पराए बन जाते हैं।",
      "जब दिल टूटता है, तो हर वादा बेमिसाल हो जाता है।",
      "भरोसे पर खड़ा हर रिश्ता, धोखे की बुनियाद पर ढह जाता है।",
      "सच्चे प्यार की पहचान धोखे के वक्त होती है।",
      "जिसने धोखा दिया, उसकी यादें भी अब बोझ लगती हैं।",
      "वफादारी का सिला कभी-कभी धोखे में छिपा होता है।",
      "जब अपनों से ही मिलती है ठेस, तो क्या करें हम इस हद तक?",
      "धोखे की चोट गहरी होती है, लेकिन उसे भुलाना भी जरूरी होता है।",
      "हर मुस्कान के पीछे छुपा होता है एक दर्द, जो धोखे ने दिया।",
      "वो चेहरे पर हंसी रखते हैं, पर दिल में धोखा छिपाए रखते हैं।",
      "धोखा देने वालों की एक आदत होती है, सच्चाई को छिपाना।",
      "कभी-कभी दोस्ती में भी धोखा मिलता है, जब भरोसा टूट जाता है।",
      "भरोसा टूटने पर रिश्ते भी टूट जाते हैं, जैसे कांच के बर्तन।",
      "धोखे की परछाई में सच्चाई कहीं खो जाती है।",
      "जो अपनों ने दिया धोखा, वो पल दिल को चीर देता है।",
      "हर बार धोखा मिलने पर हम सिख लेते हैं एक नया सबक।",
      "धोखा खाने के बाद भी मुस्कुराने का हौसला रखना चाहिए।",
      "धोखा देने वालों से यही सीख मिली, अपनों पर विश्वास न करें।",
      "रिश्ते मजबूत होते हैं विश्वास से, पर एक धोखा सब कुछ बदल देता है।",
      "जो धोखा देते हैं, वो खुद को कभी नहीं पहचान पाते।"
    ],
    "BetrayalShayariAllListEnglish": [
      "Betrayal is the silent killer of relationships.",
      "Trust is like a paper; once crumpled, it can’t be perfect again.",
      "The hardest part about betrayal is that it never comes from your enemies.",
      "Betrayal is a choice, not an accident.",
      "When someone betrays you, it’s a reminder of your own strength.",
      "The pain of betrayal is a lesson in disguise.",
      "A betrayal cuts deeper than any knife.",
      "Trust is built on honesty, and betrayal shatters that trust.",
      "When loyalty fades, betrayal often takes its place.",
      "Betrayal leaves scars that time can never heal.",
      "In the end, betrayal teaches you the true value of trust.",
      "Sometimes, the people you trust the most end up hurting you the deepest.",
      "Betrayal can only happen if you trust someone.",
      "Every betrayal begins with trust.",
      "The worst feeling is being betrayed by the person you trusted the most.",
      "Betrayal turns friends into strangers.",
      "It’s sad when you realize you weren’t as important to someone as you thought.",
      "Betrayal shows the true face of a friend.",
      "Don’t be afraid to let go of someone who betrays your trust.",
      "Betrayal is a reminder that not everyone has good intentions.",
    ],

    "MemoryShayariAllListHindi": [
      "यादें भी एक अजीब चीज हैं, कभी मुस्कुराती हैं, कभी रुलाती हैं।",
      "यादों के सफर में, कुछ पल ऐसे होते हैं जो कभी नहीं भूलते।",
      "जब भी यादें ताजा होती हैं, दिल में एक खालीपन सा महसूस होता है।",
      "यादों का महल भी कितना खूबसूरत होता है, पर कभी-कभी दर्द भी दे जाता है।",
      "कुछ यादें इतनी प्यारी होती हैं कि वो हमेशा जिंदा रहती हैं।",
      "कभी-कभी यादों की बारिश में भीगना अच्छा लगता है।",
      "यादें जख्म तो देती हैं, लेकिन खुशियों का अहसास भी कराती हैं।",
      "कुछ लम्हे ऐसे होते हैं, जिन्हें याद कर मुस्कुराना पड़ता है।",
      "यादें दिल की गहराई में बसी होती हैं, जो कभी नहीं मिटती।",
      "भले ही वक्त बदल जाए, पर यादें हमेशा साथ रहती हैं।",
      "यादों की दुनिया में खो जाना ही सच्ची खुशी है।",
      "जब भी तुम्हारी याद आती है, दिल की धड़कन तेज हो जाती है।",
      "यादें हमें जीने का एक और मौका देती हैं।",
      "कभी-कभी यादें हमें ये एहसास दिलाती हैं कि हम अकेले नहीं हैं।",
      "यादों के साये में जीने का अपना ही मजा है।",
      "यादें तो हमेशा रहेंगी, बस उनसे जुड़ी बातें भूल जाएं।",
      "कभी हंसकर, कभी रोकर, यादों का सफर चलती रहती है।",
      "यादें हमें भले ही तड़पाती हों, पर वो भी हमारी कहानी होती हैं।",
      "जो यादें दिल में बसी हैं, वो कभी नहीं जाती।",
      "यादें एक खजाना होती हैं, जो समय के साथ और भी मूल्यवान हो जाती हैं."
    ],
    "MemoryShayariAllListEnglish": [
      "Memories are timeless treasures of the heart.",
      "Some memories are like stars, shining brightly in the darkest nights.",
      "In the garden of memories, some flowers never fade.",
      "The bittersweet taste of memories lingers in the heart.",
      "Memories are the whispers of the past, echoing in our souls.",
      "Every memory is a part of the story that makes us who we are.",
      "Sometimes, the best way to hold onto memories is to let them go.",
      "Memories are the footprints of our past that guide us forward.",
      "Every moment becomes a memory that we cherish forever.",
      "In the book of life, memories are the pages we turn back to.",
      "Memories can bring a smile or a tear; they are the essence of life.",
      "The beauty of memories lies in their ability to evoke emotions.",
      "We may forget the moments, but we will never forget the memories.",
      "In the silence of solitude, memories speak the loudest.",
      "The heart remembers what the mind forgets.",
      "Memories are like shadows, always following us.",
      "In every heartbeat, there’s a memory waiting to be cherished.",
      "Memories can fade, but the feelings they bring will remain.",
      "Each memory is a brushstroke in the canvas of our life.",
      "Memories are the threads that weave the fabric of our existence.",
    ],

    "GulzarShayariAllListHindi": [
      "तुम्हारे बिना, ये ज़िंदगी अधूरी है, जैसे बादल बिना बारिश के।",
      "हर ख्वाब की एक हकीकत होती है, पर हकीकत के ख्वाब कभी अधूरे नहीं होते।",
      "सफर में खुशबू की तरह बिखर जाओ, यादों में छुपकर मुस्कुराते रहो।",
      "इश्क का ये आलम है, हर लम्हा तेरा ही दीदार चाहता है।",
      "दिल की बातों को आँखों में बसा लेना, ये भी तो इश्क का एक अंदाज़ है।",
      "तुमसे मिलकर समझा, इश्क क्या होता है, तुम्हारी यादों में सारा जहां बसा है।",
      "हर शब्द में तेरी खुशबू है, जैसे फूलों में बसी हो बहार।",
      "कभी तो आओ, इस दिल की तन्हाई को चुराने के लिए।",
      "तेरे बिना अधूरा है मेरा हर लम्हा, तू ही तो है मेरी खुशी का कारण।",
      "प्यार के रंगों से सजाए हैं हमने ख्वाब, तुम्हारे बिना सब बेकार हैं।",
      "तेरे बिना जो मिले, वो महफ़िल अधूरी है, जैसे चाँद बिना रात का।",
      "तेरे साथ चलकर, हर रास्ता आसान लगता है।",
      "तुम्हारी यादों का साया, मेरे हर ख्वाब में बसा है।",
      "दिल की धड़कन को समझो, वो तुम्हारा नाम लेती है।",
      "तुम हो तो सब कुछ है, वरना ये दुनिया बेकार है।",
      "गुलजार की शायरी में छुपा है इश्क का जज़्बात।",
      "तेरे बिना ज़िंदगी का कोई रंग नहीं, जैसे बारिश बिना बादल का।",
      "तुम्हारी मुस्कान में छुपी है सारा जहां।",
      "हर लम्हा तुम्हारे बिना अधूरा लगता है।",
      "तुमसे मिलकर जाना, इश्क की सच्चाई क्या होती है।"
    ],
    "GulzarShayariAllListEnglish": [
      "In every silence, your name whispers softly in my heart.",
      "Love is not just a feeling; it's a beautiful journey.",
      "With you, every moment is a poetic verse written by the heart.",
      "Memories of you linger like a fragrant breeze in my soul.",
      "You are the melody in my life’s song, making every note meaningful.",
      "Every tear shed is a reflection of the love we once shared.",
      "In the garden of dreams, you are the most beautiful flower.",
      "Your smile paints my world in colors I never knew existed.",
      "Love is a fragile thing, yet it holds the power to heal.",
      "In your absence, every moment feels like an eternity.",
      "The stars shine brighter when I think of you at night.",
      "Your laughter is the music that dances in my heart.",
      "Every love story is beautiful, but ours is my favorite.",
      "In the chaos of life, your love is my peaceful sanctuary.",
      "Your memories are like pages in a book I never want to close.",
      "Every heartbeat carries a whisper of your love.",
      "The beauty of love lies in its ability to inspire and uplift.",
      "With you, every day is a new beginning, full of hope.",
      "Your love is the light that guides me through the darkest nights.",
      "In the tapestry of my life, you are the brightest thread.",
    ],

    "RomanticShayariAllListHindi": [
      "तेरी मोहब्बत में हर रंग है, जैसे बहारों में फूलों की खुशबू।",
      "जब से तुझसे मिला हूँ, मेरे सपनों में बस तू ही तू है।",
      "तेरे बिना ये दिल अधूरा है, जैसे चाँद बिना रात का।",
      "तू जो पास होती है, हर दर्द को भुला देती है।",
      "तेरे बिना हर लम्हा बंजर है, जैसे बरसात बिना कोई मैदान।",
      "तुझसे मिलकर समझा, प्यार क्या होता है, हर ख्वाब में तेरा ही जिक्र होता है।",
      "तेरी आँखों की गहराई में डूब जाना चाहता हूँ, तू मेरी मोहब्बत है, ये मैं कबूल करना चाहता हूँ।",
      "सिर्फ तेरा नाम लूँ जुबां से, ये पल हर पल मुझे मोहब्बत का अहसास कराता है।",
      "तेरी हँसी से रोशन होता है मेरा जहाँ, तू मेरी ज़िंदगी की सबसे हसीन कहानी है।",
      "तू जो साथ हो, हर मुश्किल आसान लगती है।",
      "तेरे बिना इस दिल का क्या है, ये तो बस एक खामोशी है।",
      "तेरे इश्क में हर दर्द को खुशी में बदल दिया मैंने।",
      "जब तू मुस्कुराती है, मेरा दिल भी मुस्कुराने लगता है।",
      "तू मेरी मोहब्बत की पहली और आखिरी ख्वाहिश है।",
      "तेरी बाहों में पाकर, हर लम्हा जन्नत का एहसास होता है।",
      "तेरे बिना ज़िंदगी का कोई रंग नहीं, जैसे बारिश बिना बादल का।",
      "तेरे बिना हर सुबह अधूरी है, जैसे सूरज बिना सुबह का।",
      "तेरी यादों में बसा है मेरा सारा जहां।",
      "तू ही मेरा ख्वाब है, और मैं तेरा सच्चा दीवाना।",
      "तेरे साथ बिताया हर लम्हा, मेरी ज़िंदगी का सबसे हसीन पल है।"
    ],
    "RomanticShayariAllListEnglish": [
      "In your eyes, I see my forever; in your heart, I find my home.",
      "Every moment with you is like a beautiful dream come true.",
      "You are the melody to my heart, the rhythm to my soul.",
      "With you, even silence speaks volumes of love.",
      "Your smile lights up my darkest days, bringing joy to my heart.",
      "Every kiss we share is a promise of love that lasts forever.",
      "You are my favorite place to go when my mind searches for peace.",
      "In your arms, I find solace and a love that feels like magic.",
      "You are the reason behind my smiles and the muse for my dreams.",
      "Loving you is not just a choice; it's a beautiful necessity.",
      "Every heartbeat whispers your name, echoing the love we share.",
      "With you, every day feels like a new beginning, full of hope.",
      "You are the sun that brightens my world, the moon that calms my soul.",
      "In this journey of love, you are my destination.",
      "Your laughter is the sweetest music, playing in my heart.",
      "Together, we write the most beautiful chapters of our love story.",
      "You are my dream come true, the love I've always sought.",
      "In the garden of my heart, you are the most beautiful flower.",
      "With you, love feels like an endless adventure.",
      "You are my heartbeat, the rhythm that guides my life.",
    ],

    "WeddingShayariAllListHindi": [
      "बंदन तो है प्यार का, पर ये रिश्ता और भी प्यारा है।",
      "तेरे संग बिताया हर लम्हा अब एक याद बन गया है।",
      "शादी का ये पवित्र बंधन, हर दिल को एक नई पहचान देता है।",
      "तू संग है जब, हर दिन जैसे जश्न होता है।",
      "सपनों की दुनिया में, तू मेरा राजकुमार है।",
      "तेरे बिना मेरी दुनिया अधूरी है, जैसे चाँद बिना रात का।",
      "शादी के बाद, हर सुबह तेरे चेहरे की मुस्कान से होती है।",
      "प्यार में डूबकर, हम एक नई जिंदगी की शुरुआत कर रहे हैं।",
      "तेरा हाथ थामकर चलना, ये जीवन का सबसे सुंदर सफर है।",
      "इस रिश्ते की मिठास, जैसे मीठी बर्फी की टुकड़ी।",
      "शादी के इस बंधन में, सच्चा प्यार और विश्वास हो।",
      "तू मेरी खुशियों की वजह है, मेरे हर ख्वाब की हकीकत।",
      "तेरे बिना ये दिल बेताब है, जैसे बारिश बिना बादल का।",
      "सपनों का ये राजकुमार, अब मेरी ज़िंदगी का हिस्सा बन गया है।",
      "हमारा रिश्ता है प्यार का, इसमें कोई कमी नहीं होनी चाहिए।",
      "तेरे साथ चलना, जैसे किसी हसीन सफर पर निकलना।",
      "शादी का ये पवित्र बंधन, दिलों को एक-दूसरे से जोड़ता है।",
      "तेरे बिना मेरी खुशी अधूरी है, जैसे सूरज बिना सुबह का।",
      "साथ तेरा हो, तो हर मुश्किल आसान लगती है।",
      "शादी की इस नई शुरुआत पर, दिल से तुमको बधाई।"
    ],
    "WeddingShayariAllListEnglish": [
      "In this beautiful bond of love, we find our forever.",
      "Together, we create memories that will last a lifetime.",
      "This wedding is not just a ceremony; it's a celebration of love.",
      "With you by my side, every day feels like a fairytale.",
      "You are my partner, my love, my best friend.",
      "In your eyes, I see my future and my dreams.",
      "This union is the beginning of a beautiful journey.",
      "Together, we will dance through life with love in our hearts.",
      "You are the missing piece to my heart's puzzle.",
      "In this moment, we become one soul, forever intertwined.",
      "May our love grow stronger with each passing day.",
      "With every promise made, my heart blooms with joy.",
      "You are my sunshine, lighting up my darkest days.",
      "In this sacred bond, we find strength and happiness.",
      "Together, we will build a life filled with love and laughter.",
      "Every moment spent with you is a treasure to cherish.",
      "This wedding is a testament to our unwavering love.",
      "You are the dream I never want to wake up from.",
      "May our hearts beat in unison, forever in love.",
      "With you, I have found my happily ever after."
    ],

    "PrayerShayariAllListHindi": [
      "खुदा से बस यही दुआ है, हर कदम पर तेरा साथ मिले।",
      "तेरी रहमत से हर मुश्किल आसान हो जाए, यही मेरी प्रार्थना है।",
      "खुदा के दर पर जो सच्चे दिल से मांगता है, उसे कभी निराश नहीं लौटना पड़ता।",
      "तेरी मेहरबानी से हर दर्द मिट जाए, यही दुआ है मेरी।",
      "प्रभु तेरा आशीर्वाद सदा मेरे साथ रहे, ये मेरी प्रार्थना है।",
      "हर सुबह की शुरुआत तेरी याद से हो, यही है मेरी चाहत।",
      "खुदा से तुझको खुशियों का रास्ता मिले, यही प्रार्थना है।",
      "हर मुश्किल में तेरा साथ मिले, ये मेरा आस्था का फल है।",
      "तेरी दुआ से हर सपना साकार हो जाए, यही है मेरी उम्मीद।",
      "संसार में हर इंसान को तेरा प्यार मिले, यही मेरी प्रार्थना है।",
      "प्रभु, हर दिल को शांति और सुकून का अहसास कराएं।",
      "खुदा से मेरी यही इच्छा है, हर अंधेरा सुबह में बदले।",
      "तेरी कृपा से हर रोग दूर हो, यही मेरी विनती है।",
      "हर दिन को एक नई शुरुआत मिले, यही मेरी प्रार्थना है।",
      "प्रभु, सबको अपनी छांव में रखो, यही मेरी दुआ है।",
      "तेरे रास्ते पर चलने का हौसला दे, ये मेरी प्रार्थना है।",
      "खुदा, मुझे औरों की मदद करने की ताकत दे।",
      "तेरी रहमत से हर ख्वाब सच हो जाए, यही मेरी उम्मीद है।",
      "प्रभु, सबकी खुशियों का ख्याल रखना, यही मेरी प्रार्थना है।",
      "खुदा, तू सदा मेरे और मेरे परिवार के साथ रह।"
    ],
    "PrayerShayariAllListEnglish": [
      "In every prayer, I find hope and strength to carry on.",
      "May your blessings guide me through life's challenges.",
      "I pray for peace and love to fill every heart.",
      "With faith in my heart, I seek your divine grace.",
      "In times of trouble, I turn to you for comfort.",
      "Every prayer is a step closer to my dreams.",
      "May your light shine upon me, leading the way.",
      "I offer my gratitude for all the blessings I receive.",
      "In the silence of my heart, I find your presence.",
      "With every breath, I seek your divine love.",
      "May you grant strength to those in need.",
      "In your mercy, I find solace and healing.",
      "I pray for the well-being of all my loved ones.",
      "Every prayer is a whisper of my soul to you.",
      "May your guidance be with me on this journey.",
      "In my moments of doubt, I seek your wisdom.",
      "With faith, I surrender my worries to you.",
      "May your love wrap around me like a warm embrace.",
      "I pray for a world filled with kindness and compassion.",
      "In every heartbeat, I feel your love and grace.",
    ],

    "LonelinessShayariAllListHindi":[
      "तन्हाई में जब भी सोचा तुम्हें, हर दर्द को फिर से जी लिया। तिमसे मिली थी जो खुशी, उससे तन्हाई ने मेरी जी लिया।",
      "तेरा ख्याल जब आता है, तन्हाई और भी गहराती है। तेरे बिना ये जिंदगी, बस एक सुनसान सी राह बन जाती है।",
      "तन्हाई में यूं ही वक्त गुजारता हूं, खामोशियों से बातें कर लिया करता हूं। तेरे बिना ये दिल बहुत उदास है, बस तेरे ही ख्यालों में खुद को समझा लिया करता हूं।",
      "जब से तुम दूर गए हो, हर पल की तन्हाई ने मेरा पीछा किया। तेरे बिना हर खुशी अधूरी है, इस दिल ने बस तन्हाई से ही दोस्ती की।",
      "एक तन्हाई है जो साए की तरह है, तेरे बिना ये दिल अधूरा सा है। हर वक्त तुम्हारी यादों में खोया हूं, तन्हाई में ही खुद को खोया सा है।",
      "दिल की आवाज सुनकर तन्हाई की बातें, हर लम्हा तुम्हारी यादें सजाए रखती हैं। किससे कहें अपनी तन्हाई की दास्तान, हर किसी से बस यही बातें छुपाए रखती हैं।",
      "तन्हाई की शाम में खामोश रह जाता हूं, तेरे ख्वाबों में खोकर मुस्कुराता हूं। तू तो नहीं है मेरे पास, पर तेरे बिना ये दिल तन्हा रह जाता है।",
      "एक तन्हाई का साया है, जो हर वक्त मेरे साथ है। तेरी यादों में खोया हूं, बस यही मेरा साथ है।",
      "तेरी यादों की तन्हाई में, हर दर्द को मैंने सहा है। तेरे बिना ये दुनिया है वीरान, तन्हाई में ही मैंने जीना सीखा है।",
      "तन्हाई में हर लम्हा बीत जाता है, तेरे बिना ये दिल अधूरा सा रह जाता है। तेरी यादों का साया मेरे साथ है, बस इसी तन्हाई में मैं जी जाता हूं।",
      "तन्हाई में बसी है मेरी कहानी, हर लफ्ज़ में है तेरी निशानी। तेरे बिना हर खुशी अधूरी है, इस दिल की तन्हाई है बहुत बड़ी।",
      "जब भी देखूं तारे आसमान में, मुझे याद आता है तेरा नज़ारा। तन्हाई में बुनते हैं ख्वाब हम, तेरा साथ पाकर होता है सारा।",
      "तेरी यादों का सिलसिला खत्म नहीं होता, तन्हाई की रातों में ये दर्द नहीं होता। तू दूर है मुझसे, फिर भी पास है, इस दिल के हर कोने में तेरा एहसास है।",
      "कभी सोचा नहीं था तन्हाई में जी लूंगा, पर तेरा नाम लूँगा और मुस्कुराऊंगा। बिना तन्हाई के ये दिल अधूरा सा है, बस तेरी यादों के सहारे जी लूंगा।",
      "तन्हाई के अंधेरों में खो गया हूं मैं, तेरे बिना हर खुशी को भुला दिया है मैंने। जिंदगी की राहों पर बस तन्हाई का साया है, अब तो बस तेरे ही ख्यालों में जीता हूं मैं।",
      "तन्हाई ने सिखाया है जीना, हर दर्द को अब सहना है। तेरे बिना ये दुनिया सुनसान है, बस तेरे ख्यालों में अपना सारा जीवन है।",
      "तन्हाई में खोया हूं, पर तुझसे उम्मीद नहीं छोड़ता। तू लौट आएगी, इस विश्वास में जीता हूं, हर पल की तन्हाई को खुद से सहता हूं।",
      "दिल की हर धड़कन में तेरा नाम है, तन्हाई की हर रात में तेरा एहसास है। तू दूर है मुझसे, पर इस दिल के करीब है, बस यही तन्हाई अब मेरा नसीब है।",
      "तन्हाई का साथी बन गया है मेरा दिल, तेरे बिना हर खुशी लगती है अधूरी। इस दुनिया में सब कुछ है, पर तन्हाई ही है जो, अब मेरी सबसे करीबी दोस्त बन गई है।",
      "तेरे बिना हर बात अधूरी है, इस दिल की तन्हाई का कोई साथी नहीं। सिर्फ तेरे ख्यालों से ही चलती है मेरी जिंदगी, तन्हाई का ये आलम कभी खत्म नहीं।",
    ],
    "LonelinessShayariAllListEnglish":[
      "In solitude, when I think of you, I relive every pain anew. The joy you gave me once, now in loneliness, it feels like a trance.",
      "When your thoughts cross my mind, loneliness deepens, hard to find. Without you, life feels so bland, a deserted path, I cannot stand.",
      "In solitude, I pass my time, talking to silence feels like a rhyme. Without you, my heart's in dismay, in memories of you, I drift away.",
      "Since you left, every moment's a chase, loneliness follows like a shadow's trace. Without you, every joy is incomplete, with solitude, I find a bittersweet beat.",
      "There's a loneliness, like a shadow's guise, without you, my heart's an empty surprise. Lost in your memories, I try to find, in solitude, a comfort I bind.",
      "Listening to my heart's silent refrain, loneliness shares my every pain. Whom do I tell my tale of despair? In silence, my secrets lay bare.",
      "In the quiet of the night, I remain, lost in dreams, a smile I feign. You're not here, yet my heart beats slow, in your absence, loneliness does grow.",
      "There's a shadow of solitude that stays, always with me, through endless days. Lost in thoughts of you, I find my way, in this loneliness, I choose to sway.",
      "In the solitude of your memories, I sigh, enduring every pain, with a tearful eye. This world feels empty, devoid of cheer, in loneliness, I've learned to persevere.",
      "Every moment in solitude, I count, without you, my heart feels like a mount. With the shadow of your memories, I stay, in this loneliness, I find my way.",
      "In solitude, my story unfolds, every word whispers your memories untold. Without you, every joy feels incomplete, this loneliness in my heart, I can't defeat.",
      "I never thought I’d live in solitude, but I say your name and smile in the mood. Without loneliness, my heart feels so bare, only in your memories, do I find my care.",
      "The stars remind me of you at night, weaving dreams of you in this quiet light. In loneliness, I create my dreams, for with you, my life forever beams.",
      "I’ve lost every joy in this solitude's hold, forgetting every happiness, my heart has grown cold. Life’s paths are dark, loneliness my only friend, hoping you'll return, on this I depend.",
      "Loneliness has taught me to endure, every pain and sorrow, it feels so pure. In your absence, the world feels so empty, living in your memories, is where I find plenty.",
      "In solitude, I've become my own best friend, every moment spent in your thoughts, I commend. Without you here, my heart feels less alive, yet in the shadows of my heart, your memories thrive.",
      "Every heartbeat whispers your name, loneliness embraces me, fueling this flame. You’re far away, but close to my heart, in this solitude, we’ll never be apart.",
      "Loneliness has become my closest friend, in this world without you, where will it end? With memories of you, I will survive, in this solitude, I strive to revive.",
      "Every moment in solitude, I see, the world’s emptiness reflects in me. Yet in your thoughts, I find a way, to keep this loneliness at bay.",
      "Though the world is full, I feel alone, in this solitude, my heart has grown. But your memories, like stars, shine bright, guiding me through the loneliest night.",
    ],

    "BirthdayShayariAllListHindi": [
      "जन्मदिन की खुशियों से भरी हो ये जिंदगी, हर पल में बस तू ही तू हो।",
      "तेरे जन्मदिन पर तुझे मिले खुशियों के सभी रंग, हर दिन तेरी जिंदगी हो खुशनुमा।",
      "तेरे जन्मदिन पर ये दुआ है मेरी, तेरा हर सपना हो पूरा और हर दिन हो नई खुशियां।",
      "हर साल की तरह इस साल भी, तेरा जन्मदिन खास हो और तू हमेशा खुश रहे।",
      "खुश रहो तुम हमेशा, जैसे चाँद की चाँदनी से रात खिल जाती है।",
      "तेरे जन्मदिन पर खुदा से बस यही दुआ है, तेरा जीवन खुशियों से भरा हो।",
      "हर साल की तरह इस साल भी, तेरा जन्मदिन मनाने का मौका मिले।",
      "जन्मदिन की शुभकामनाएँ, तेरा हर दिन हो प्यार भरा।",
      "तेरे जन्मदिन पर मिले तुझे सच्चा प्यार और सच्ची खुशियां।",
      "तेरा हर सपना पूरा हो, ये मेरी दिल से दुआ है।",
      "तू खुश रहे, ये मेरा जन्मदिन का उपहार है।",
      "जन्मदिन की हार्दिक शुभकामनाएं, जीवन में हमेशा मुस्कुराओ।",
      "हर पल तेरा मुस्कुराना, हर दिन तेरा खिलखिलाना, यही है मेरी चाहत।",
      "जन्मदिन पर तेरी खुशियों की फुहार हो, जीवन में हो सदा बहार।",
      "खुशियों का ये दिन, तेरा दिन है, इसे मनाने में कोई कमी ना हो।",
      "तू हमेशा हंसता रहे, यही है मेरी इच्छा।",
      "तेरे जन्मदिन पर सजें फूलों की तरह खुशियाँ।",
      "जन्मदिन पर मिले तुझे सबकुछ, जो तेरा दिल चाहता है।",
      "तेरे लिए हर दिन एक नई शुरुआत हो, ये मेरी दुआ है।",
      "खुश रहो, खिलखिलाओ, यही है जन्मदिन की मेरी शुभकामना।"
    ],
    "BirthdayShayariAllListEnglish": [
      "May this birthday bring you joy and all your heart desires.",
      "On your special day, may happiness surround you like a warm embrace.",
      "Wishing you a birthday filled with love, laughter, and endless blessings.",
      "Another year older, another year wiser, may your dreams come true.",
      "Happy birthday! May your life be as beautiful as a blooming flower.",
      "On this special day, may you be surrounded by loved ones and good vibes.",
      "Wishing you a year ahead filled with adventure and unforgettable moments.",
      "Happy birthday to someone who brings so much joy to our lives.",
      "May your birthday be the start of a year filled with good luck and happiness.",
      "On your birthday, I wish you endless success and happiness.",
      "Every day is a gift, but your birthday is a special reminder of how loved you are.",
      "Wishing you a day that’s as special as you are, filled with joy and surprises.",
      "May this birthday be a beautiful chapter in your life’s story.",
      "Happy birthday! May you always find reasons to smile.",
      "Celebrate your day with all the joy and happiness you deserve.",
      "On this day, may you reflect on all your accomplishments and plan for the future.",
      "Wishing you love, happiness, and all the best on your birthday.",
      "May every moment of your special day be filled with joy and laughter.",
      "Happy birthday! Embrace the new year of life with a happy heart.",
      "Here's to a fabulous birthday and a year full of adventures."
    ],

    "FestivalShayariAllListHindi": [
      "त्योहारों की रौनक हो, खुशियों का संसार हो। हर दिल में प्यार हो, ये दीवाली का त्योहार हो।",
      "हर पर्व पर छाए खुशियों के रंग, संग में हो सबके, यही हो हमारी अभिलाषा।",
      "त्योहारों की मिठास हो, सबके चेहरे पर मुस्कान हो। हर घर में प्रेम की खुशबू हो, यही है असली दीवाली।",
      "इस होली पर रंगों की बरसात हो, सभी के दिलों में प्यार की बात हो।",
      "त्योहारों का ये मौसम लाए खुशियां अनगिनत, सभी संग हों, यही है असली फेस्टिवल।",
      "रक्षा बंधन की इस पावन बेला पर, भाई-बहन का प्यार हो, ये हमारा सपना हो।",
      "गुलाल से भरी हो ये होली, हंसते-खिलखिलाते चेहरे हों, यही हो हमारी खुशी।",
      "दिवाली की रात सजे दीपों से, हर दिल में हो प्रेम और आपसी नफरत मिटाने की चाह।",
      "पर्वों की खुशबू में बसी हो जिंदगी, हर दिल में छाई हो एक नई रोशनी।",
      "त्योहारों का उल्लास हर मन में छाया हो, हर घर में हो प्रेम का साया।",
      "इस गणेशोत्सव पर सुख-समृद्धि की कामना, हर दिल में बसी हो सच्ची श्रद्धा।",
      "सभी त्योहारों का संदेश प्रेम और भाईचारा है, चलो मिलकर मनाएं, यही है हमारा इरादा।",
      "इस वेलेंटाइन पर प्यार की बारिश हो, दिलों में खुशियों की तरंग हो।",
      "त्योहारों का ये मौसम लाए ढेर सारी खुशियां, हर चेहरे पर हो मुस्कान और प्यार की मिठास।",
      "क्रिसमस पर बिखरे खुशियों के रंग, मिलकर मनाएं, यही है प्रेम का संग।",
      "त्योहारों की रौनक से भरी हो जिंदगी, हर दिन हो खुशी का एक नया सफर।",
      "इस दशहरे पर बुराई पर अच्छाई की जीत हो, सभी में प्रेम और सम्मान की बात हो।",
      "पर्वों का ये मौसम सिखाता है एकता का पाठ, सब मिलकर मनाएं, यही है हमारी सच्ची बात।",
      "इस ईद पर हो एक नई शुरुआत, सभी के दिल में बसी हो एक नई बात।",
      "हर त्योहार पर मिले सच्चे रिश्तों की खुशबू, यही है हमारी असली दुआ।"
    ],
    "FestivalShayariAllListEnglish": [
      "May the festival bring you joy and happiness in abundance.",
      "On this festive day, let love and laughter fill the air.",
      "Every festival is a reminder to cherish the moments with loved ones.",
      "May the colors of this festival brighten your life with joy.",
      "Let’s celebrate together, embracing the spirit of unity and love.",
      "On this occasion, may your heart be filled with joy and gratitude.",
      "May every celebration be a reminder of the blessings we have.",
      "Wishing you a festival full of sweet memories and laughter.",
      "May the lights of the festival guide you towards happiness and peace.",
      "Every festival is a chance to renew our bonds of love and friendship.",
      "Celebrate the joy of togetherness during this festive season.",
      "May your life be filled with colors of happiness and success.",
      "This festival, let’s spread joy and kindness to everyone around us.",
      "Wishing you all the happiness this festival can bring.",
      "Let’s create beautiful memories this festival with our loved ones.",
      "On this festive occasion, may your dreams come true.",
      "Let the spirit of the festival fill your heart with joy.",
      "May the blessings of the festival be with you always.",
      "Embrace the spirit of love and togetherness this festival.",
      "Wishing you peace, happiness, and joy during this festival."
    ],

    "PatrioticShayariAllListHindi": [
      "तिरंगे की शान में हम सब कुर्बान हैं, भारत की हर एक सांस में हमें पहचान है।",
      "मेरा देश, मेरी पहचान, इस पर मेरा हर एक क़दम है शान।",
      "गर्व से कहते हैं हम, हम भारतीय हैं, इस मिट्टी की हर बूंद में हमारी जान है।",
      "वतन की महक में बसी है मेरी जान, हर लहर में गूंजे मेरा हिंदुस्तान।",
      "भारत की धरा पर हो जब तिरंगा लहराए, दिलों में देशभक्ति की आग जगाए।",
      "खुशबू की तरह बसी है ये देश की मिट्टी, जब भी इसकी याद आए, मन में भर जाए ख़ुशी।",
      "सिर उठाकर चलना यही हमारी पहचान है, हर भारतीय की खून में बसी है देशभक्ति की जान।",
      "शहीदों की शहादत को न भूलेंगे हम, हर पल देश के लिए जीते रहेंगे हम।",
      "राखी का धागा हो या तिरंगा, हम सबको जोड़े ये देश का रंग।",
      "मातृभूमि के खातिर जो लड़े, वही असली योद्धा हैं।",
      "जब भी सुनूं तिरंगे की बातें, दिल में उमंगें लहराए।",
      "सैनिकों की कुर्बानी से सजती है ये धरती, वतन की महिमा में बसी है हमारी हर क़िस्मत।",
      "हम भारत के लोग, हर दिल में बसी है देशभक्ति की ताकत।",
      "इस धरती पर बसने वाले, सबकी पहचान है भारत।",
      "जब भी गूंजे तिरंगा, हमें गर्व से सर उठाने का मौका मिले।",
      "हम भारत के लोग, हमारी एकता ही है हमारी शक्ति।",
      "धन्य है वो मातृभूमि, जो हमें देती है जीने की वजह।",
      "देशभक्ति की भावना को मन में सदा रखें, हम सभी मिलकर इसे सजाएंगे।",
      "जब तिरंगा लहराए, हर भारतीय का दिल धड़क जाए।",
      "हम सब मिलकर बनाएं भारत को और भी महान।"
    ],
    "PatrioticShayariAllListEnglish": [
      "With pride, we stand united, our love for the nation ignited.",
      "In every heartbeat, our country resonates, India is where our identity celebrates.",
      "We are proud to be Indians, our land, our strength, our band.",
      "In the fragrance of our homeland, we find our true essence.",
      "When the flag waves high, our spirits soar to the sky.",
      "The soil of our nation whispers love, a blessing from above.",
      "Walking tall with our heads high, the spirit of patriotism never runs dry.",
      "We remember the sacrifices, of those who gave their lives for our rising sun.",
      "Whether it's a festival or a fight, our tricolor shines bright.",
      "True warriors are those who fight for their motherland's light.",
      "Every time I hear the national anthem, my heart swells with pride.",
      "This land of diversity is our strength, our unity is our might.",
      "In every challenge, we find our resolve, to keep our nation's pride involved.",
      "The love for our country is what makes us whole, it gives our lives a goal.",
      "With every flutter of the flag, we pledge to never lag.",
      "We are the voices of our nation, united in our determination.",
      "Blessed is the land that gives us purpose and peace.",
      "In patriotism, we find our true selves, a bond that never shelves.",
      "When the flag waves, our hearts race, filled with love for this place.",
      "Together, let's make our India shine, with love and pride divine."
    ],

    "SadShayariAllListHindi": [
      "कितनी मुश्किल से जीते हैं हम, तुमसे दूर रहकर भी मुस्कुराते हैं हम।",
      "दिल के दर्द को छुपाना नहीं आता, हम बस खुद से ही बातें करते हैं।",
      "तेरे बिना ये जिंदगी अधूरी लगती है, हर ख्वाब में तेरा ही साया होता है।",
      "हमने खुद को खो दिया है तेरे बिना, तन्हाई में हर पल रोया है।",
      "खुश रहने की कोशिश में, दिल की हर खुशी खो दी।",
      "तन्हाई की इस रात में, बस तेरे ख्यालों में खोई रहती हूँ।",
      "सपनों में तेरा चेहरा आता है, आंखों से आंसू फिर भी निकल जाता है।",
      "किसी ने कहा था, दर्द कभी नहीं भुलता, यही सच है, यही सच्चाई है।",
      "तेरे बिना अधूरा है मेरा हर पल, जिंदगी का कोई अर्थ नहीं है।",
      "हमारी खुशियों की लकीरें अब मिट गई हैं, दर्द के साये में हर सुबह बित गई है।",
      "तेरे जाने का ग़म अब बर्दाश्त नहीं होता, तन्हाई में जीने का कोई और रास्ता नहीं होता।",
      "खुद को भुलाकर जीते हैं हम, लेकिन इस दिल के जख्म छुपाए नहीं जाते।",
      "तेरे बिना ये शहर सुना लगता है, हर गली में तेरा ही नाम सुनाई देता है।",
      "कभी हंसकर देखो, तो समझ आ जाएगा, छिपा हुआ दर्द क्या होता है।",
      "तेरी यादों के साए में अब जीते हैं, खुद को खोते जाते हैं।",
      "तन्हाई के इस सफर में हम हमेशा साथ हैं, लेकिन दर्द के साथ हर कदम में हार हैं।",
      "दिल की सुनता नहीं कोई, बस खामोशी की सजा भुगतता है।",
      "तू छूट गई, और हम खुद को समझाते रहे, तेरे बिना भी जी लेंगे।",
      "इस दर्द की गहराई को क्या समझेगा कोई, जब तक खुद न भुगतें।",
      "हर लम्हा तेरा इंतजार होता है, और हर इंतजार में बिखरता है दिल।"
    ],
    "SadShayariAllListEnglish": [
      "In the silence of the night, my heart whispers your name.",
      "Every smile hides a tear, every laugh conceals a fear.",
      "The shadows of your absence linger in my heart, tearing me apart.",
      "Living in memories of you, I find it hard to move on.",
      "In this world full of noise, my heart aches for your voice.",
      "The emptiness you left behind is a void I can't fill.",
      "Tears flow like rivers, drowning my hope and will.",
      "In the crowd, I feel alone, searching for a heart to call my own.",
      "Every night, I dream of you, but morning brings me back to the blue.",
      "You left without saying goodbye, and I'm left with unanswered why.",
      "Every moment feels like an eternity, without you here with me.",
      "I wear a smile to hide the pain, but deep inside, it’s all in vain.",
      "Your memories haunt me like a ghost, making my heart long for you the most.",
      "In the silence of my heart, your absence speaks the loudest.",
      "I try to forget, but your love is a tattoo that won't fade.",
      "Even in a room full of people, I feel lost without you.",
      "Hope was once my anchor, but now it's my sinking ship.",
      "In every sunset, I see your face; in every dawn, I miss your embrace.",
      "Life without you feels like a song without a melody.",
      "The hardest goodbyes are the ones that are left unspoken."
    ],

    "LoveShayariAllListHindi": [
      "तेरी मोहब्बत में मैंने खुद को खो दिया है, हर एक पल में बस तेरा ही ख्वाब देखा है।",
      "तेरे बिना ये दिल अधूरा सा लगता है, तुझे देखूं तो हर ग़म भुला सा लगता है।",
      "जब से देखा है तुम्हें, दिल की धड़कन तेज हो गई है, ये मोहब्बत है या जादू, समझ नहीं आ रहा।",
      "तू जो पास होती है, हर परेशानी दूर होती है, तेरी मुस्कान से ही मेरी दुनिया रोशन होती है।",
      "तेरे बिना जीना अब संभव नहीं है, तुम मेरी ज़िंदगी की सबसे खूबसूरत कहानी हो।",
      "तुम्हारे ख्यालों में खोकर, मैं हर दर्द भूल जाता हूँ, तुम्हारी मोहब्बत में खुद को पा जाता हूँ।",
      "तेरे चेहरे की रोशनी, मेरे जीवन की खुशबू है, तेरे साथ बिताया हर लम्हा, मेरे दिल की धड़कन है।",
      "जब भी तुम्हें देखता हूँ, दिल में कुछ-कुछ होता है, ये मोहब्बत है या कुछ और, समझ नहीं आता।",
      "तुम्हारे साथ बिताए हर पल की कीमत समझी है, मेरे दिल की हर धड़कन में तुम्हारा नाम बसता है।",
      "तुम मेरी ज़िंदगी में आए हो जैसे कोई ख्वाब, तेरे साथ हर लम्हा है सबसे खास।",
      "तेरी मोहब्बत ने मुझे सिखाया है जीना, तुम हो तो मुझे कोई भी ग़म नहीं है।",
      "तेरे बिना हर खुशी अधूरी है, तेरा साथ हो तो हर दर्द में भी खुशियाँ भरी हैं।",
      "जब तुम पास होते हो, हर मुश्किल आसान लगती है, तुम्हारी मोहब्बत से मेरी जिंदगी में बहार आती है।",
      "तुम्हारे बिना ये दिल तन्हा है, मेरी दुआओं में सिर्फ तुम हो, यही सच है।",
      "तेरे साथ बिताया हर लम्हा, मेरी सबसे बड़ी खुशी है, तेरी मोहब्बत में मिली मुझे जिंदगी की सच्चाई है।",
      "तू मेरी आँखों की रोशनी है, मेरे दिल की धड़कन है, तेरे बिना जीना अब असंभव है।",
      "तुम्हारी हंसी में छुपा है मेरा सुकून, तुम्हारे बिना ये दिल है बहुत ही सून।",
      "तेरी मोहब्बत ने दी है मुझे नया नजरिया, तेरा साथ मिल गया तो हर ग़म है अजनबीयता।",
      "तू मेरी ज़िंदगी का वो ख्वाब है, जिसे मैं हर पल जीता हूँ, तेरे बिना हर खुशी अधूरी है।"
    ],
    "LoveShayariAllListEnglish": [
      "In your love, I found my true self, every moment spent with you is a treasure.",
      "Without you, my heart feels incomplete, your presence makes every sorrow sweet.",
      "Since I laid my eyes on you, my heart races, is it love or magic, I wonder in all the right places.",
      "When you're near, all my worries fade away, your smile lights up my darkest day.",
      "Living without you seems impossible, you are the most beautiful story in my life, so irresistible.",
      "Lost in your thoughts, I forget all my pain, in your love, I find myself again.",
      "The light of your face is the fragrance of my life, every moment with you cuts through my strife.",
      "Whenever I see you, my heart skips a beat, is it love or something deeper? I'm left to repeat.",
      "I’ve learned the value of every moment spent with you, your name resonates in every heartbeat, so true.",
      "You came into my life like a beautiful dream, every second with you feels like a perfect theme.",
      "Your love taught me how to live, with you by my side, I have so much to give.",
      "Without you, every joy feels incomplete, your presence makes every pain feel obsolete.",
      "When you are near, every challenge seems easy, your love brings a joy that's so pleasing.",
      "In my prayers, it's only you I ask, the truth is, life without you is a daunting task.",
      "Every moment spent with you is my biggest delight, your love is my strength, my guiding light.",
      "You are the sunshine that brightens my day, without you, every path feels so gray.",
      "Your laughter holds my peace, without you, my heart never finds ease.",
      "In your love, I discovered a new perspective, with you by my side, every pain feels selective.",
      "You are the dream I cherish the most, with every heartbeat, it's your name I boast.",
      "With you, I've found my forever, in love, we shall always endeavor."
    ],
  };

  static List emoji=[
    "🤪😜🤓🤗🫸🌲🎾",
    "🧑‍🦲🌚🌻🌩️🐲🐎🦘🌒",
    "🪔☎️🖥️🎛️💎🧰📿",
    "🧑‍🎨🧑‍✈️🧝‍♀️🧑‍⚕️👥🐞",
    "🪔☎️🖥️🎛️💎🧰📿🪟",
    "🧑‍🎨🧑‍✈️🧝‍♀️🧑‍⚕️👥",
    "🚀🧚‍♂️🐇🍿🏄‍♂️💼🌅",
    "🚁🐋🍣🦋🚒🏇🥨",
    "🏖️🥑🧑‍⚖️🍭🧀🧄",
    "🦉🪁🏓🛹🧃🍍",
    "🎲🍀🧸🦄🎈",
    "🦩🛳️🐕🍬🎺🎷",
    "🦚🦅🛥️🧊🍉🧑",
    "🐘🐳🪂🎧🎥🧑‍",
    "🪟🎛️⚓🚤🚃🎗️🎖️",
    "🐚🐫🥃🍧🏂",
    "🎛️⚓🚤🚃🎗️🎖️",
    "🐞🐚🐫🥃🍧🏂",
    "💿💡🖨️🔔🍕",
    "🍦🧘‍♀️🖍️💻🎨",
    "🦑🎩🎉📱⚽🍩",
    "🍔🦖📀🏆🎼🎮",
    "🍇🦀🪙🧋🧑‍🚀📚🎬",
    "🍓🧑‍🏭🍰🛼🛏️🐢",
    "‍🔬🍒🧋🧁🍱🐘🌵",
    "💻🛴🍕🌼🎿🏊‍♂️🛴"
  ];

  static List<Color> bgColorNameList = [
    Color.fromARGB(255, 24, 29, 61),
    Color.fromARGB(255, 30, 35, 72),
    Color.fromARGB(255, 40, 48, 89),
    Color.fromARGB(255, 56, 62, 105),
    Color.fromARGB(255, 72, 81, 128),
    Color.fromARGB(255, 18, 22, 48),
    Color.fromARGB(255, 89, 96, 145),
    Color.fromARGB(255, 45, 51, 102),
    Color.fromARGB(255, 70, 78, 120),
    Color.fromARGB(255, 58, 66, 110),
    Color.fromARGB(255, 34, 39, 83),
    Color.fromARGB(255, 15, 20, 40),
    Color.fromARGB(255, 47, 53, 92),
    Color.fromARGB(255, 63, 70, 110),
    Color.fromARGB(255, 79, 87, 125),
    Color.fromARGB(255, 20, 25, 53),
    Color.fromARGB(255, 96, 104, 157),
    Color.fromARGB(255, 50, 58, 98),
    Color.fromARGB(255, 12, 16, 34),
    Color.fromARGB(255, 81, 90, 139),
    Color.fromARGB(255, 43, 47, 78),
    Color.fromARGB(255, 64, 70, 110),
    Color.fromARGB(255, 27, 31, 63),
    Color.fromARGB(255, 91, 98, 149),
    Color.fromARGB(255, 15, 19, 45),
    Color.fromARGB(255, 52, 60, 104),
    Color.fromARGB(255, 108, 115, 167),
    Color.fromARGB(255, 44, 49, 90),
    Color.fromARGB(255, 17, 20, 43),
    Color.fromARGB(255, 76, 83, 130),
    Color.fromARGB(255, 67, 74, 122),
    Color.fromARGB(255, 29, 33, 67),
    Color.fromARGB(255, 55, 61, 101),
    Color.fromARGB(255, 111, 119, 168),
    Color.fromARGB(255, 92, 99, 144),
    Color.fromARGB(255, 48, 54, 97),
    Color.fromARGB(255, 22, 26, 55),
    Color.fromARGB(255, 87, 93, 140),
    Color.fromARGB(255, 60, 66, 105),
    Color.fromARGB(255, 32, 36, 70),
    Color.fromARGB(255, 49, 56, 93),
  ];

  static List<Color> textColorNameList = [
    Color.fromARGB(255, 255, 255, 255), // White
    Color.fromARGB(255, 240, 240, 240), // Light Gray
    Color.fromARGB(255, 200, 200, 200), // Silver
    Color.fromARGB(255, 255, 69, 0),    // Red-Orange
    Color.fromARGB(255, 34, 139, 34),   // Forest Green
    Color.fromARGB(255, 70, 130, 180),  // Steel Blue
    Color.fromARGB(255, 255, 215, 0),   // Gold
    Color.fromARGB(255, 255, 20, 147),  // Deep Pink
    Color.fromARGB(255, 148, 0, 211),   // Dark Violet
    Color.fromARGB(255, 135, 206, 250), // Light Sky Blue
    Color.fromARGB(255, 255, 105, 180), // Hot Pink
    Color.fromARGB(255, 100, 149, 237), // Cornflower Blue
    Color.fromARGB(255, 255, 228, 225), // Misty Rose
    Color.fromARGB(255, 135, 211, 124), // Light Green
    Color.fromARGB(255, 75, 0, 130),    // Indigo
    Color.fromARGB(255, 221, 160, 221), // Plum
    Color.fromARGB(255, 255, 182, 193), // Light Pink
    Color.fromARGB(255, 255, 228, 181), // Light Peach
    Color.fromARGB(255, 0, 255, 255),   // Cyan
    Color.fromARGB(255, 135, 206, 235), // Light Blue
    Color.fromARGB(255, 139, 69, 19),   // Saddle Brown
  ];





  static List<String> numberInHindi = [
    '१',
    '२',
    '३',
    '४',
    '५',
    '६',
    '७',
    '८',
    '९',
    '१०',
    '११',
    '१२',
    '१३',
    '१४',
    '१५',
    '१६',
    '१७',
    '१८',
    '१९',
    '२०',
    '२१',
    '२२',
    '२३',
    '२४',
    '२५'
  ];


}
